# Generated by Django 3.2.4 on 2021-06-29 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_taskconditional_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='lesson',
        ),
    ]
