# Generated by Django 3.2.4 on 2021-06-29 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_remove_user_lesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
