# Generated by Django 3.2.5 on 2021-07-06 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20210705_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='appraisal',
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer_content',
            field=models.CharField(default=0, max_length=2048, verbose_name='Содержание ответа'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='from_range',
            field=models.FloatField(default=0, verbose_name='Начало диапазона'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='is_true',
            field=models.BooleanField(default=False, verbose_name='Верный ответ'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='to_range',
            field=models.FloatField(default=0, verbose_name='Конец диапазона'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='description',
            field=models.CharField(max_length=2048, verbose_name='Описание урока'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='order_number',
            field=models.PositiveSmallIntegerField(verbose_name='Номер урока'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(max_length=124, verbose_name='Название урока'),
        ),
        migrations.AlterField(
            model_name='task',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='students.lesson'),
        ),
        migrations.AlterField(
            model_name='task',
            name='order_number',
            field=models.PositiveSmallIntegerField(verbose_name='Номер задания'),
        ),
        migrations.AlterField(
            model_name='task',
            name='question',
            field=models.CharField(max_length=2048, verbose_name='Вопрос задания'),
        ),
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('number', 'number'), ('string', 'string'), ('range', 'range'), ('custom', 'custom')], max_length=40, verbose_name='Тип ответа'),
        ),
        migrations.AlterField(
            model_name='taskconditional',
            name='appraisal',
            field=models.FloatField(default=0, verbose_name='Оценка за урок'),
        ),
        migrations.AlterField(
            model_name='taskconditional',
            name='pessimizing_factor',
            field=models.FloatField(default=0, verbose_name='Пессимизирующий фактор'),
        ),
        migrations.AlterField(
            model_name='taskconditional',
            name='status_task',
            field=models.BooleanField(default=False, verbose_name='Сдача задания'),
        ),
        migrations.AlterField(
            model_name='taskconditional',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_conds', to='students.task'),
        ),
        migrations.AlterField(
            model_name='taskconditional',
            name='user_answer',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='Ответ студента'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True, verbose_name='Email адрес'),
        ),
    ]
