# Generated by Django 3.2.4 on 2021-06-29 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_remove_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='required_id',
        ),
    ]
