# Generated by Django 3.2.4 on 2021-06-30 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_remove_user_required_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='appraisal',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer_content',
            field=models.CharField(default=0, max_length=2048),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='description',
            field=models.CharField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='task',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson', to='students.lesson'),
        ),
        migrations.AlterField(
            model_name='taskconditional',
            name='appraisal',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='taskconditional',
            name='pessimizing_factor',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='total_appraisal',
            field=models.FloatField(default=0),
        ),
    ]
