# Generated by Django 3.2.4 on 2021-06-30 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_auto_20210630_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='from_range',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='answer',
            name='to_range',
            field=models.FloatField(default=0),
        ),
    ]
