# Generated by Django 3.2.4 on 2021-06-30 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_auto_20210630_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='user_answer',
            field=models.CharField(default=0, max_length=2048),
        ),
    ]
